baseURL = "https://monaparty.me/"
languageCode = "en-us"
title = "Monaparty Portal | Crypto asset platform based on Counterparty, Monacoin"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
#    [[menu.nav]]
#        name    = "About"
#        url     = "/about"
#        weight  = 2
#    [[menu.nav]]
#        name    = "Service"
#        url     = "/service"
#        weight  = 3
#    [[menu.nav]]
#        name    = "Gallery"
#        url     = "/gallery"
#        weight  = 4
#    [[menu.nav]]
#        name    = "Blog"
#        url     = "/blog"
#        weight  = 5
#    [[menu.nav]]
#        name    = "Contact"
#        url     = "/contact"
#        weight  = 6

# Site Params
[params]
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "Airspace Hugo theme"
    author = "Themefisher"
    # Google Analitycs
    googleAnalitycsID = "UA-52736825-3"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/20171007_monaparty.png"
#        heading = "HI, MY NAME IS JONATHON & I AM A"
#        description = "WITH 10 YEARS EXPERIENCE, I'VE OCCUPIED MANY ROLES INCLUDING DIGITAL DESIGN DIRECTOR, WEB DESIGNER AND DEVELOPER. THIS SITE SHOWCASES SOME OF MY WORK."
        btn     = false
        btnText = "Open Your Wallet"
        btnURL  = "https://wallet.monaparty.me/"
#        [[params.banner.flipText]]
#            title   = "DESIGNER"
#        [[params.banner.flipText]]
#            title   = "DEVELOPER"
#        [[params.banner.flipText]]
            title   = "FATHER"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT MONAPARTY"
        content = "Monaparty is a crypto-asset platform based on <a href='https://counterparty.io/' target='_blank'>Counterparty</a> and stored on <a href='https://monacoinproject.org'>Monacoin</a> blockchain. <br/><br/> Monaparty is an open platform. API is open and maintained by some members. <br/><br/>And Monaparty is an ecosystem. Powerful users provides their services using Monaparty."
        image   = "images/about/about.jpg"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "WANT TO START YOUR MONAPARTY LIFE ?"
        content = "The first step is to create your wallet. One of the easiest way is to use Counterwallet-mona, our official wallet."
        btnText = "Start Monaparty with Counterwallet-mona"
        btnURL  = "https://wallet.monaparty.me/"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = false
        title   = "Latest Works"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    